# Dispara a pipeline automaticamente quando houver commit na branch 'master'
trigger:
  branches:
    include:
      - master

# Variáveis usadas no pipeline
variables:
  environment: 'prod'
  webAppName: 'petshop-webapp-prod'
  resourceGroup: 'rg-peton-prod'
  azureSubscription: 'AzureServiceConnection-Prod'

# Tipo de máquina
pool:
  vmImage: 'ubuntu-latest'

steps:
  # Instala o Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Instalar Node.js v22.x'

  # Instala dependências dentro da pasta do projeto
  - script: |
      cd petshop
      node -v
      npm install
    displayName: 'Instalar dependências do Vue.js'

  # Gera a build (gera a pasta /dist)
  - script: |
      cd petshop
      npm run build
    displayName: 'Build do projeto Vue.js'

  # Copia a pasta dist para o staging
  - task: CopyFiles@2
    displayName: 'Copiar arquivos da build para staging'
    inputs:
      contents: '**'
      sourceFolder: 'petshop/dist'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  # Cria o zip do conteúdo da build
  - task: ArchiveFiles@2
    displayName: 'Arquivar build para deploy'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/petshop/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/vueapp.zip'
      replaceExistingArchive: true

# Deploy para Azure Static Web App
  - task: AzureStaticWebApp@0
    displayName: 'Deploy para Azure Static Web App (Prod)'
    inputs:
      azure_static_web_apps_api_token: $(STATIC_WEBAPP_TOKEN)  # Token secreto
      app_location: "/petshop"          # pasta do projeto Vue
      output_location: "dist"           # pasta gerada pelo build (npm run build)
      skip_app_build: true              # já fez o build antes no pipeline
