# Dispara a pipeline automaticamente quando houver commit na branch 'develop'
trigger:
  branches:
    include:
      - develop

# Variáveis usadas no pipeline — edite conforme seu projeto
variables:
  environment: 'dev'
  webAppName: 'petshop-webapp-dev'               # Nome do App Service no Azure (Web App para o ambiente de desenvolvimento)
  resourceGroup: 'rg-peton-dev'                       # Nome do Resource Group (opcional neste pipeline)
  azureSubscription: 'AzureServiceConnection-Dev'     # Nome da Service Connection configurada no Azure DevOps Dev

# Define o tipo de máquina usada para rodar o pipeline
pool:
  vmImage: 'ubuntu-latest'


steps:
  # Instala o Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Instalar Node.js v22.x'

  # Instala dependências dentro da pasta do projeto
  - script: |
      cd petshop
      node -v
      npm install
    displayName: 'Instalar dependências do Vue.js'

  # Gera a build (gera a pasta /dist)
  - script: |
      cd petshop
      npm run build
    displayName: 'Build do projeto Vue.js'

  # Copia a pasta dist para o staging
  - task: CopyFiles@2
    displayName: 'Copiar arquivos da build para staging'
    inputs:
      contents: '**'
      sourceFolder: 'petshop/dist'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  # Cria o zip do conteúdo da build
  - task: ArchiveFiles@2
    displayName: 'Arquivar build para deploy'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/petshop/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/vueapp.zip'
      replaceExistingArchive: true

# Deploy para Azure Static Web App
  - task: AzureStaticWebApp@0
    displayName: 'Deploy Vue para Azure Static Web App'
    inputs:
      azure_static_web_apps_api_token: $(STATIC_WEBAPP_TOKEN)
      app_location: "petshop"          # Onde está o package.json
      output_location: "dist"          # Onde o Vue gera o index.html
