name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: docker build -t petmob/petshop-front:latest .

      - name: Push da imagem
        run: docker push petmob/petshop-front:latest

      - name: Deploy na EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull petmob/petshop-front:latest
            docker stop petshop-front-container || true
            docker rm petshop-front-container || true
            docker run -d \
              --network pet-network \
              -p 3000:80 \
              --name petshop-front-container \
              petmob/petshop-front:latest